export default [{
        title: 'Git',
        folder: 'git',
        description: 'Einführung in das Versionskontrollsystem Git',
        tags: ['Versionskontrolle', 'Softwareentwicklung', 'Collaboration'],
        author: 'chatGPT',
        github: '',
    },
    {
        title: '@media-Queries',
        folder: 'media-queries',
        description: '@media-Queries ist ein CSS-Konzept, das es ermöglicht, das Aussehen und Layout einer Webseite basierend auf der Größe des Viewports des Geräts zu ändern.',
        tags: ['CSS', 'Webdesign', 'Layout'],
        author: 'chatGPT',
        github: 'https://github.com/caitoor/ig3_prog3_lexikon',
    },
    {
        title: 'Library jQuery',
        folder: 'jQuery',
        description: 'jQuery ist eine umfangreiche JavaScript-Bibliothek, die die Webentwicklung durch DOM-Manipulation, Event-Handling, Animationen, Effekte und AJAX erleichtert und dadurch ein dynamisches Benutzererlebnis ermöglicht.',
        tags: ['JavaScript-Bibliothek', 'Event-Handling', 'Interaktive Webanwendungen'],
        author: 'Anja Gutmann',
        github: 'https://github.com/anjagutmann/jQuery.git',
    },
    {
        title: 'Repository',
        folder: 'repository',
        description: 'Ein Repository ist eine zentrale Ablage in dem digitale Daten verwaltet werden.',
        tags: ['Versionskontrolle', 'Software Development', 'Collaboration', 'Data'],
        author: 'Anna Ligon',
        github: 'https://github.com/annxligon/repository.git',
    },
    {
        title: 'Margin & Padding',
        folder: 'margin_padding',
        description: 'Mit Margin und Padding kann man festlegen wo welche Elemente auf der Homepage mit welchem Abstand sind.',
        tags: ['Layout', 'HTML', 'CSS', 'Webdesign'],
        author: 'Nina Hielscher',
        github: 'https://github.com/NinaHielscher/URL.git',
    },
    {
        title: 'Test',
        folder: 'test',
        description: 'Lorem ipsum dolor sit amet ...',
        tags: ['HTML', 'CSS', 'JavaScript'],
        author: 'Fabian Rauch',
        github: 'https://github.com/caitoor/ig3_prog3_lexikon',
    },
    {
        title: 'URL',
        folder: 'Url_Svelte',
        description: 'URL steht für Uniform Resource Locator und ist eine Zeichenkette, die verwendet wird, um eine bestimmte Ressource im Internet zu identifizieren.',
        tags: ['Internet', 'Webadresse', 'HTML'],
        author: 'Nina Hielscher',
        github: 'https://github.com/NinaHielscher/URL.git',
    }
];